export enum Path {
  HomePage = '/',
  BucketPAge = 'bucket',
  CheckoutPage = 'checkout',
  PaymentPage = 'payment',
  RegistrationPage = 'registration',
  RestorePasswordPAge = 'restore-password',
  OrdersPage = 'orders',
  FavoritesPage = 'favorites',
  PersonalDataPage = 'personal-data',
  BlogsPage = 'blog',
  BlogId = ':blogId',
  ConcreteBlogPage = 'blog/:blogId',
  PromosPage = 'promos',
  PromoId = ':promoId',
  ConcretePromoPage = 'promos/:promoId',
  ContactsPage = 'contacts',
  CategoryPage = 'category/:categoryId',
  SubCategoryPathWithId = 'sub-category/:sub-categoryId',
  SubCategoryPage = 'category/:categoryId/sub-category/:sub-categoryId',
  ProductPathWithId = 'product/:productId',
  ConcreteProductPage = 'category/:categoryId/sub-category/:sub-categoryId/product/:productId',
  DeliveryPage = 'delivery',
  WholesalersPage = 'wholesalers',
  AboutUsPage = 'about',
  ReturnGoodsPage = 'return-goods',
  NotFoundPage = '*',
}
