export enum Path {
  HomePage = '/',
  CartPage = 'cart',
  NewOrderPage = 'new-order',
  PaymentPage = 'payment',
  RegistrationPage = 'registration',
  RestorePasswordPage = 'restore-password',
  OrdersPage = 'orders',
  FavoritesPage = 'favorites',
  PersonalDataPage = 'personal-data',
  BlogsPage = 'blog',
  BlogId = ':blogId',
  ConcreteBlogPage = 'blog/:blogId',
  PromosPage = 'promos',
  PromoId = ':promoId',
  ConcretePromoPage = 'promos/:promoId',
  ContactsPage = 'contacts',
  CategoryPage = 'category/:categoryId',
  SubCategoryPathWithId = 'subCategory/:subCategoryId',
  SubCategoryPage = 'category/:categoryId/subCategory/:subCategoryId',
  ProductPathWithId = 'product/:productId',
  ConcreteProductPage = 'category/:categoryId/subCategory/:subCategoryId/product/:productId',
  DeliveryPage = 'delivery',
  WholesalersPage = 'wholesalers',
  AboutUsPage = 'about',
  ReturnGoodsPage = 'return-goods',
  NotFoundPage = '*',
}
